# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/free_rtos_v1/free_rtos_v1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==free_rtos_v1 || ORIG_REF_NAME==free_rtos_v1} -quiet] -quiet

# IP: bd/free_rtos_v1/ip/free_rtos_v1_processing_system7_0_0/free_rtos_v1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==free_rtos_v1_processing_system7_0_0 || ORIG_REF_NAME==free_rtos_v1_processing_system7_0_0} -quiet] -quiet

# XDC: /home/kike/Desktop/marvin/vivado_project/pynqZ2_platform/pynqZ2_platform.gen/sources_1/bd/free_rtos_v1/free_rtos_v1_ooc.xdc
