# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.srcs/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/pynq_z2_bram_axi_smc_0.xci
# IP: The module: 'pynq_z2_bram_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/bd_646f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_0/bd_646f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_1/bd_646f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_2/bd_646f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_3/bd_646f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_4/bd_646f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_5/bd_646f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_6/bd_646f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_7/bd_646f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_8/bd_646f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_9/bd_646f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_10/bd_646f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_11/bd_646f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_12/bd_646f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_1/bd_646f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_1/bd_646f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_5/bd_646f_s00a2s_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_6/bd_646f_sarn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_6/bd_646f_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_7/bd_646f_srn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_7/bd_646f_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_8/bd_646f_sawn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_8/bd_646f_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_9/bd_646f_swn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_9/bd_646f_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_10/bd_646f_sbn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_10/bd_646f_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_11/bd_646f_m00s2a_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_z2_bram_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_z2_bram_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.srcs/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/pynq_z2_bram_axi_smc_0.xci
# IP: The module: 'pynq_z2_bram_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/bd_646f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_0/bd_646f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_1/bd_646f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_2/bd_646f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_3/bd_646f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_4/bd_646f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_5/bd_646f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_6/bd_646f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_7/bd_646f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_8/bd_646f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_9/bd_646f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_10/bd_646f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_11/bd_646f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_12/bd_646f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_1/bd_646f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_1/bd_646f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_5/bd_646f_s00a2s_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_6/bd_646f_sarn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_6/bd_646f_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_7/bd_646f_srn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_7/bd_646f_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_8/bd_646f_sawn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_8/bd_646f_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_9/bd_646f_swn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_9/bd_646f_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_10/bd_646f_sbn_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_10/bd_646f_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/bd_0/ip/ip_11/bd_646f_m00s2a_0_ooc.xdc

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_z2_bram_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_z2_bram_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
