# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.srcs/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_bram_ctrl_0_bram_0/pynq_z2_bram_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'pynq_z2_bram_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_bram_ctrl_0_bram_0/pynq_z2_bram_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_z2_bram_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.srcs/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_bram_ctrl_0_bram_0/pynq_z2_bram_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'pynq_z2_bram_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/ip/pynq_z2_bram_axi_bram_ctrl_0_bram_0/pynq_z2_bram_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_z2_bram_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
