# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pynq_z2_bram/pynq_z2_bram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_z2_bram || ORIG_REF_NAME==pynq_z2_bram} -quiet] -quiet

# IP: bd/pynq_z2_bram/ip/pynq_z2_bram_processing_system7_0_0/pynq_z2_bram_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_z2_bram_processing_system7_0_0 || ORIG_REF_NAME==pynq_z2_bram_processing_system7_0_0} -quiet] -quiet

# IP: bd/pynq_z2_bram/ip/pynq_z2_bram_axi_bram_ctrl_0_0/pynq_z2_bram_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_z2_bram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==pynq_z2_bram_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/pynq_z2_bram/ip/pynq_z2_bram_axi_bram_ctrl_0_bram_0/pynq_z2_bram_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_z2_bram_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==pynq_z2_bram_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/pynq_z2_bram/ip/pynq_z2_bram_axi_smc_0/pynq_z2_bram_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_z2_bram_axi_smc_0 || ORIG_REF_NAME==pynq_z2_bram_axi_smc_0} -quiet] -quiet

# IP: bd/pynq_z2_bram/ip/pynq_z2_bram_rst_ps7_0_100M_0/pynq_z2_bram_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_z2_bram_rst_ps7_0_100M_0 || ORIG_REF_NAME==pynq_z2_bram_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/kike/Desktop/marvin/vivado_project/pynq_z2_bram/pynq_z2_bram.gen/sources_1/bd/pynq_z2_bram/pynq_z2_bram_ooc.xdc
