# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kike/Desktop/marvin/vivado_project/pynqZ2_platform/pynqZ2_platform.srcs/sources_1/bd/free_rtos_v1/ip/free_rtos_v1_processing_system7_0_0/free_rtos_v1_processing_system7_0_0.xci
# IP: The module: 'free_rtos_v1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynqZ2_platform/pynqZ2_platform.gen/sources_1/bd/free_rtos_v1/ip/free_rtos_v1_processing_system7_0_0/free_rtos_v1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'free_rtos_v1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/kike/Desktop/marvin/vivado_project/pynqZ2_platform/pynqZ2_platform.srcs/sources_1/bd/free_rtos_v1/ip/free_rtos_v1_processing_system7_0_0/free_rtos_v1_processing_system7_0_0.xci
# IP: The module: 'free_rtos_v1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kike/Desktop/marvin/vivado_project/pynqZ2_platform/pynqZ2_platform.gen/sources_1/bd/free_rtos_v1/ip/free_rtos_v1_processing_system7_0_0/free_rtos_v1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'free_rtos_v1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
